### ISSUE TITLE
stem.socketerror: connection refused

### ISSUE THREAD

**Issue by maumau35** [Juniorn1003/Faitagram#32] opened 2018-01-17 20:53 UTC
You fixed the first thing, but with that this came up.
Traceback (most recent call last):
  File "faitagram", line 25, in <module>
    controller = Controller.from_port(port=9051)
  File "/usr/local/lib/python2.7/dist-packages/stem/control.py", line 1026, in from_port
    control_port = stem.socket.ControlPort(address, port)
  File "/usr/local/lib/python2.7/dist-packages/stem/socket.py", line 376, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/stem/socket.py", line 247, in connect
    self._socket = self._make_socket()
  File "/usr/local/lib/python2.7/dist-packages/stem/socket.py", line 405, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [Errno 111] Connection refused

There is something wrong with the ports. it should be 9051 and 9050, and it is 9051 and 9050 so think there is and error in the code

**Comment by Juniorn1003** [comment] 2018-01-18 00:28
I actually did not figure out this.... Well, after I figure out this problem it will work PERFECTLY. The duplicate of this question is hshehab's question, go to that. #13

**Comment by Juniorn1003** [comment] 2018-01-18 00:29
This is an issue, so I should not technically close it, but there is a same issue, lets go there and talk about it.

**Closed by Juniorn1003** 2018-01-18 00:29 UTC
Labels: duplicate, enhancement
