### ISSUE TITLE
real ip or tor ip ?

### ISSUE THREAD

**Issue by smokeabird** [Juniorn1003/Faitagram#19] opened 2018-01-08 13:31 UTC
My only problem is that i cannot have a tor's ip, 

i always have my real internet ip by using ip.42.pl in my_ip. 

what do you think about it ? do i have a pb with self.setIP()?
Do i have to launch Faitagram in a root session ?

**Comment by Juniorn1003** [comment] 2018-01-08 13:45
Sorry, I just need to make the proxy in faitagram working. But the problem is that proxy is hard to set in selenium, especially when you need to keep changing the IP.
It is NOT your problem, it is the scripts. You don't need to launch it in a root session. 
Also, I am actually not allowed to close this issue since it is a issue, but there is a another issue where he is telling me the exact same issue. So can we please move to that issue? since it's hard to tell informations in two exact same issues.

**Closed** 2018-01-08 13:46 UTC

**Comment by vanguard71** [comment] 2018-01-21 18:27
Even if your fix proxy problem, I don't think current way of calling will ever print proxied ip

my_ip = urlopen("http://ip.42.pl/raw").read()

is being called before driver object being created at least in one place.   

for example, if you call like this.. it should print the tor ip address...

process = Popen(["/bin/torsocks", "/bin/curl", "-s", "-H", "User-Agent: Mozilla/5.0", "http://ip.42.pl/raw"], stdout=PIPE)
(my_ip, err) = process.communicate()

print(O + ("  Password: %s \t| Failed \t| IP : %s \n " % (password,my_ip)) + W)

I was also working to see, if we can just call the script via torsocks or torify.. but running into lower level selenium libraries and socket creation.
