### ISSUE TITLE
No connection error

### ISSUE THREAD

**Issue by fu771** [Juniorn1003/Faitagram#11] opened 2018-01-02 19:03 UTC
Installed tor, installed selenium, chmod setup.py and faitagram, python setup.py, copied geckodriver to faitagram folder, ran command line:

How can I fix?

Checking Username...

Traceback (most recent call last):
  File "faitagram", line 159, in <module>
    main()
  File "faitagram", line 47, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 66, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 77, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

**Comment by fu771** [comment] 2018-01-02 19:08
Would a donation make this easier to fix?

**Comment by Juniorn1003** [comment] 2018-01-03 17:32
No, please don't donate. By the way this is a selenium problem, will try to get some errot infos in the selenium headquarters web. I won't close this issue yet.

**Comment by Juniorn1003** [comment] 2018-01-03 21:15
setup.py is fixed, it will make the problem gone.
Please clone the script again and execute setup.py, if the issue is continuous, then please let me know again.

**Closed by Juniorn1003** 2018-01-03 21:15 UTC
